name: Periodic health check

on:
  # schedule: 
  #   - cron: '15 * * * *'
  push:
    branches: [main, feature]

jobs:
  periodic_health:
    runs-on: ubuntu-20.04
    steps:
    - name: test deployed Url
      uses: jtalk/url-health-check-action@v3
      with:
        url: https://full-stack-open-pokedex-miahro.fly.dev/healthx
        max-attempts: 3
        retry-delay: 5s
