name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]


jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly Deploy
        id: fly
        if: ${{ github.event_name == 'push' }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Discord deploy
        if: ${{ steps.fly.outcome == 'success' }}
        uses: rjstone/discord-webhook-notify@v1.0.4
        with: 
          text: A new version of Pokedex deployed
          severity: info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}


      - name: Discord failure
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1.0.4
        with: 
          text: Build failed
          severity: error
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}



  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
